main:
	pdflatex "Plantilla de Apunte.tex";

clean_junk:
	rm -f *.alt;
	rm -f *.aux
	rm -f *.def;
	rm -f *.examp;
	rm -f *.inf;
	rm -f *.lof;
	rm -f *.log;
	rm -f *.lol;
	rm -f *.lot;
	rm -f *.out;
	rm -f *.toc;

clean_pdf:
	rm -f *.pdf

clean: clean_junk clean_pdf